/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisiMisiRouteImport } from './routes/visi-misi'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SambutanRouteImport } from './routes/sambutan'
import { Route as PrestasiRouteImport } from './routes/prestasi'
import { Route as PpdbRouteImport } from './routes/ppdb'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as FasilitasRouteImport } from './routes/fasilitas'
import { Route as EkstrakurikulerRouteImport } from './routes/ekstrakurikuler'
import { Route as IndexRouteImport } from './routes/index'

const VisiMisiRoute = VisiMisiRouteImport.update({
  id: '/visi-misi',
  path: '/visi-misi',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SambutanRoute = SambutanRouteImport.update({
  id: '/sambutan',
  path: '/sambutan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestasiRoute = PrestasiRouteImport.update({
  id: '/prestasi',
  path: '/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbRoute = PpdbRouteImport.update({
  id: '/ppdb',
  path: '/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const FasilitasRoute = FasilitasRouteImport.update({
  id: '/fasilitas',
  path: '/fasilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const EkstrakurikulerRoute = EkstrakurikulerRouteImport.update({
  id: '/ekstrakurikuler',
  path: '/ekstrakurikuler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ekstrakurikuler': typeof EkstrakurikulerRoute
  '/fasilitas': typeof FasilitasRoute
  '/kontak': typeof KontakRoute
  '/ppdb': typeof PpdbRoute
  '/prestasi': typeof PrestasiRoute
  '/sambutan': typeof SambutanRoute
  '/tentang': typeof TentangRoute
  '/visi-misi': typeof VisiMisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ekstrakurikuler': typeof EkstrakurikulerRoute
  '/fasilitas': typeof FasilitasRoute
  '/kontak': typeof KontakRoute
  '/ppdb': typeof PpdbRoute
  '/prestasi': typeof PrestasiRoute
  '/sambutan': typeof SambutanRoute
  '/tentang': typeof TentangRoute
  '/visi-misi': typeof VisiMisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ekstrakurikuler': typeof EkstrakurikulerRoute
  '/fasilitas': typeof FasilitasRoute
  '/kontak': typeof KontakRoute
  '/ppdb': typeof PpdbRoute
  '/prestasi': typeof PrestasiRoute
  '/sambutan': typeof SambutanRoute
  '/tentang': typeof TentangRoute
  '/visi-misi': typeof VisiMisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ekstrakurikuler'
    | '/fasilitas'
    | '/kontak'
    | '/ppdb'
    | '/prestasi'
    | '/sambutan'
    | '/tentang'
    | '/visi-misi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ekstrakurikuler'
    | '/fasilitas'
    | '/kontak'
    | '/ppdb'
    | '/prestasi'
    | '/sambutan'
    | '/tentang'
    | '/visi-misi'
  id:
    | '__root__'
    | '/'
    | '/ekstrakurikuler'
    | '/fasilitas'
    | '/kontak'
    | '/ppdb'
    | '/prestasi'
    | '/sambutan'
    | '/tentang'
    | '/visi-misi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EkstrakurikulerRoute: typeof EkstrakurikulerRoute
  FasilitasRoute: typeof FasilitasRoute
  KontakRoute: typeof KontakRoute
  PpdbRoute: typeof PpdbRoute
  PrestasiRoute: typeof PrestasiRoute
  SambutanRoute: typeof SambutanRoute
  TentangRoute: typeof TentangRoute
  VisiMisiRoute: typeof VisiMisiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visi-misi': {
      id: '/visi-misi'
      path: '/visi-misi'
      fullPath: '/visi-misi'
      preLoaderRoute: typeof VisiMisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sambutan': {
      id: '/sambutan'
      path: '/sambutan'
      fullPath: '/sambutan'
      preLoaderRoute: typeof SambutanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestasi': {
      id: '/prestasi'
      path: '/prestasi'
      fullPath: '/prestasi'
      preLoaderRoute: typeof PrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb': {
      id: '/ppdb'
      path: '/ppdb'
      fullPath: '/ppdb'
      preLoaderRoute: typeof PpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fasilitas': {
      id: '/fasilitas'
      path: '/fasilitas'
      fullPath: '/fasilitas'
      preLoaderRoute: typeof FasilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekstrakurikuler': {
      id: '/ekstrakurikuler'
      path: '/ekstrakurikuler'
      fullPath: '/ekstrakurikuler'
      preLoaderRoute: typeof EkstrakurikulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EkstrakurikulerRoute: EkstrakurikulerRoute,
  FasilitasRoute: FasilitasRoute,
  KontakRoute: KontakRoute,
  PpdbRoute: PpdbRoute,
  PrestasiRoute: PrestasiRoute,
  SambutanRoute: SambutanRoute,
  TentangRoute: TentangRoute,
  VisiMisiRoute: VisiMisiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
